### ISSUE TITLE
Turn input field into text box

### ISSUE THREAD

**Issue by elimisteve** [cryptag/leapchat#59]

**Comment by jimmcgaw** [comment]
I remember toying around with this originally when it was backchannel. Biggest issue with a textarea element is that hitting "enter" by default doesn't send the message, it gives you a newline.

We can externalize the "Send" action by putting in a button, which probably makes more sense anyway. It also permits newlines in messages, which isn't possible with text inputs. It's just a big UX question.

**Comment by elimisteve** [comment]
I see. I like what Slack does: enter sends a message, but you can type shift-enter to get a newline and paste in multi-line text no problem. How about that?

**Comment by jimmcgaw** [comment]
Just saw Slack comment. I'll look into it.

**Comment by elimisteve** [comment]
Looking at your PR!

**Comment by elimisteve** [comment]
@jimmcgaw Added! https://github.com/cryptag/leapchat/pull/61/commits/d23904c5a4e85671e9828a4de51a837d49e72623

**Comment by LinuxOnTheDesktop** [comment]
> Biggest issue with a textarea element is that hitting "enter" by default doesn't send the message, it gives you a newline.

 _I was about to request multi-line messages as a feature_. I can create a new issue for that, if required.

Context: I want to use leapChat for online teaching (because other secure messaging clients are too confusing and/or broken and/or expensive and/or insecure) and I do not wish to limit my pupils to single-line comments.
