### ISSUE TITLE
Don't Store Username in localStorage

### ISSUE THREAD

**Issue by jimmcgaw** [cryptag/leapchat#73]
This was mentioned at some point by elimisteve as a security issue. Perhaps the solution is to move this into persistence once we have it?

**Comment by elimisteve** [comment]
The main security/privacy issue I was worried about involved someone deanonymizing themselves by using one username in one context, then using LeapChat in another context, and having their same username be automatically re-used.

But this was fixed in https://github.com/cryptag/leapchat/commit/b16e4116a617f5a2a131ae5d94aff5413e3b1ce1

**Comment by elimisteve** [comment]
The awesome thing about localStorage is that the server can't see what's in there, unlike cookies. And both when a username is in localStorage and when it's attached to a message, the server can't see it!

> Perhaps the solution is to move this into persistence once we have it?

I can't think of a simple way to do this while still hiding the username from the server, which is a property I want to maintain even once users have their own keypairs (down the road).

For now I say we just keep using localStorage, even though it's possible to seize someone's phone and grab their username sitting on disk somewhere unencrypted.
