### ISSUE TITLE
(i) Icon Next to Logo / header

### ISSUE THREAD

**Issue by jimmcgaw** [cryptag/leapchat#83]
Brings up modal with more information.

Just make a simple component that loads markdown 
for a local file.

**Comment by elimisteve** [comment]
First draft of the markdown that should be rendered and shown when people click the `(i)` --

---

## Welcome to LeapChat!

LeapChat: encrypted, ephemeral, in-browser chat. 

Just visit leapchat.org and a new, secure chat room will instantly be created for you. And once you're in, just link people to that page to invite them to join you!

### Why LeapChat?

You shouldn't have to sacrifice your privacy and personal information just to chat online. Slack, HipChat, and others make you create an account with your email address, their software doesn't encrypt your messages (they can see everything), and the messages last forever unless you manually delete them.

In contrast, LeapChat _does_ encrypt your messages (even we can't see them!), _doesn't_ require you to give up your email address, and messages last for a maximum of 90 days (this will soon be configurable).

Plus, you can host LeapChat on your own service, since it's [open source](https://github.com/cryptag/leapchat)!

**Comment by jimmcgaw** [comment]
Looks good. I'd say the trick here is to figure out how to reuse what code we have for the "Username" overlay / modal without just copy-pasting. Though maybe we shouldn't be too clever, the two do different things.

**Comment by elimisteve** [comment]
:+1: we'll know within 2 mins of trying to make the `UsernameModal` generic whether it'll work; I agree we should try.

**Comment by elimisteve** [comment]
@Moe-Shoman "i" icon to be used just to the right of "LeapChat" fake logo: http://fontawesome.io/icon/info-circle/
